version: '3'

services:

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/cj_public/djnginx:latest
    container_name: dj-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/log:/var/log/nginx
    networks:
      - dujiao
    restart: always

  php:
    image: registry.cn-hangzhou.aliyuncs.com/cj_public/djphp74fpm:latest
    container_name: dj-php
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
      - ./php/log:/var/log/php-fpm
      - ./php/conf.d/my.ini:/usr/local/etc/php/conf.d/my.ini
      - ./php/supervisor/conf.d:/etc/supervisor/conf.d
      - ./php/supervisor/log:/var/log/supervisor
    command: ["supervisord", "-n"]
    networks:
      - dujiao
    restart: always

  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/cj_public/djmysql:latest
    container_name: dj-mysql
    expose:
      - 3306
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - dujiao
    restart: always

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/cj_public/djredis:latest
    container_name: dj-redis
    expose:
      - 6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - dujiao
    restart: always

networks:
  dujiao:
    driver: bridge
